Lab pengutronix v2 migrate
kernelci/lava-ci-staging pull request #71
Opened 2018-06-01 21:10 UTC by mgrzeschik

2018-06-01 21:13 UTC, khilman approved these changes

2018-06-04 08:28 UTC, gctucker requested changes
Sorry if it's not obvious in the templates' names, but `.json` means v1 and `.jinja2` means v2.

2018-06-04 08:28 UTC, gctucker commented on lib/device_map.py
>                                    'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
You should remove all the `json` files as these are for v1 jobs, see how other v2 devices are configured.  Then please put in the templates list only the tests you want to run, i.e. ramdisk boot, nfs boot, kselftest, other test plans...

2018-06-04 10:28 UTC, mgrzeschik commented
I reworked the changes and changed all configs to jinja2 configs including nfs and simple tests.

2018-06-04 10:43 UTC, gctucker approved these changes

2018-06-04 10:43 UTC, merged